# Add account credentials and API keys here.

# VIGO API details
CALL_REFERENCE: "1234567"
VIGO_LANGUAGE: "EnglishUnitedStates"
VIGO_AUDIO_FORMAT: "BigEndian"
REST_API_URL_BASE: "https://a9i1.voicevault.net/RestApi850/"
USERNAME: "DZqZkws5BNxPF8ExNtpq"
PASSWORD: "4KQGstT7tpyqyeFdBS9yuxmt9DDVfX"
ORGANISATION_UNIT: "f5986c00-5d18-4dc3-a02d-eceae4bb4dab"
CONFIGURATION_ID: "a1d404fa-dfbd-414c-a393-5e74886f1f35"