development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: my_verified_id_dev
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
        #- localhost:27110
        #- staging.myverifiedid.com:27017

      options:
      
test:
  sessions:
    default:
      database: mvimobile_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      hosts:
        - ec2-54-253-3-191.ap-southeast-2.compute.amazonaws.com:27017
        - ec2-54-252-43-219.ap-southeast-2.compute.amazonaws.com:27017
        - ec2-54-253-150-76.ap-southeast-2.compute.amazonaws.com:27017
      database: my_verified_id

      options:
        # The default consistency is :eventual, which means that reads will attempt to go to secondaries. 
        # If you don't want this, switch this option to :strong, which will send everything to the master node.
        # consistency: :strong
        # We can set session specific options, like reads executing
        # on secondary nodes, and defaulting the session to safe mode.
        max_retries: 1
        retry_interval: 0
